### ISSUE TITLE
Receiving error when sending basic message - was working

### ISSUE THREAD

**Issue by DanJ210** [abinoda/slack-action#19]
Hello, I've been using this. Thanks for creating btw. As of a couple days ago I had stopped receiving the message. All green checkmarks shown, no errors shown. Checking the logs shows this message and I'm not sure why. I've created an action and pasted in the example shown on documentation for this action so is there something I can do to understand what's causing this?

`{"ok":false,"error":"json_not_object","warning":"missing_charset","response_metadata":{"warnings":["missing_charset"]}}`

This is the basic action getting an error.
```
on: push
name: Slack Notification Demo
jobs:
    slackNotification:
      name: Slack Notification Demo
      runs-on: ubuntu-latest
      steps:
      - name: Notify slack
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
            args: '{\"channel\":\"GD0RL3545\",\"text\":\"Hello world\"}'
```
